const express = require("express");
const jwt = require("jsonwebtoken");
const path = require("path");
const SECRET_KEY = "iloveAnkit";


const app = express();
app.use(express.json());   // this will help the json body 

const user = [];

app.get("/", function(req, res) {
  res.sendFile(path.join(__dirname, "SignUpInpage", "index.html"));
});


app.post("/signup", function(req,res){
    const username = req.body.username;
    const password = req.body.password;

    user.push({
        username : username,
        password : password
    })

    res.json({
        message:"You are succefully signup"
    })

})

app.post("/signin", function(req,res){
    const username = req.body.username;
    const password = req.body.password;

    let founduser = user.find((u) => u.username === username && u.password === password);

    if(founduser){
        const token = jwt.sign({username}, SECRET_KEY);
        res.json({
           token: token
        })
    }else{
        res.status(403).send({
            message:"Invalid username or password"
        })
    }
})

app.get("/me", function(req,res){
    const token = req.headers.token;
    const decodedInformation = jwt.verify(token, SECRET_KEY);   // this will return the payload, after the varification that this is a valid token generated by the this SECRET_KEY,
                                                               // on the jwt.io if anyone want to decode the data from this token then he may get the payload back, but will not able to get inside becaue of the SECRET_KEY  and the token is made from both combination the payload and the SECRET_KEY
                                                               // the payload will be stored in the decodedInformation, but there may be problem if the user is decoding it and cheking it instead of verifiaction 
    const username = decodedInformation.username;

    const foundUser = user.find((u) => u.username === username);  

    if(foundUser){
        res.json({
            username:foundUser.username,
            password:foundUser.password
        })
    }else{
        res.json({
            message:"Invalid token"
        })
    }
})

app.listen(3000);